In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("Airline Dataset.csv")

In [10]:
df.head(10)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,10856,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Edithe Leggis,On Time
1,43872,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Elwood Catt,On Time
2,42633,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Darby Felgate,On Time
3,78493,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Dominica Pyle,Delayed
4,82072,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Bay Pencost,On Time
5,39630,Lora,Durbann,Female,55,Brazil,Coronel Horácio de Mattos Airport,BR,Brazil,SAM,South America,6/10/2022,LEC,Lora Durbann,On Time
6,11940,Rand,Bram,Male,73,Ivory Coast,Duxford Aerodrome,GB,United Kingdom,EU,Europe,10/30/2022,QFO,Rand Bram,Cancelled
7,26470,Perceval,Dallosso,Male,36,Vietnam,Maestro Wilson Fonseca Airport,BR,Brazil,SAM,South America,4/7/2022,STM,Perceval Dallosso,Cancelled
8,29447,Aleda,Pigram,Female,35,Palestinian Territory,Venice Marco Polo Airport,IT,Italy,EU,Europe,8/20/2022,VCE,Aleda Pigram,On Time
9,75035,Burlie,Schustl,Male,13,Thailand,Vermilion Airport,CA,Canada,NAM,North America,4/6/2022,YVG,Burlie Schustl,On Time

In [11]:
df.tail(10)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
98609,70741,Olimpia,Arstall,Female,22,China,Wuzhou Changzhoudao Airport,CN,China,AS,Asia,4/23/2022,WUZ,Olimpia Arstall,On Time
98610,87872,Che,Pressland,Male,83,France,Warangal Airport,IN,India,AS,Asia,8/5/2022,WGC,Che Pressland,Cancelled
98611,37761,Hadria,Vacher,Female,41,Canada,Ipil Airport,PH,Philippines,AS,Asia,6/6/2022,IPE,Hadria Vacher,On Time
98612,26208,Ody,Tineman,Male,82,Indonesia,Five Mile Airport,US,United States,NAM,North America,3/17/2022,FMC,Ody Tineman,Delayed
98613,95651,Oneida,Ossipenko,Female,47,Serbia,Arugam Bay SPB,LK,Sri Lanka,AS,Asia,5/12/2022,AYY,Oneida Ossipenko,Delayed
98614,58454,Gareth,Mugford,Male,85,China,Hasvik Airport,NO,Norway,EU,Europe,12/11/2022,HAA,Gareth Mugford,Cancelled
98615,22028,Kasey,Benedict,Female,19,Russia,Ampampamena Airport,MG,Madagascar,AF,Africa,10/30/2022,IVA,Kasey Benedict,Cancelled
98616,61732,Darrin,Lucken,Male,65,Indonesia,Albacete-Los Llanos Airport,ES,Spain,EU,Europe,9/10/2022,ABC,Darrin Lucken,On Time
98617,19819,Gayle,Lievesley,Female,34,China,Gagnoa Airport,CI,Côte d'Ivoire,AF,Africa,10/26/2022,GGN,Gayle Lievesley,Cancelled
98618,14485,Wilhelmine,Touret,Female,10,Poland,Yoshkar-Ola Airport,RU,Russian Federation,EU,Europe,4/16/2022,JOK,Wilhelmine Touret,Delayed

In [12]:
df.sample(5)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
13589,36030,Randa,Westhoff,Female,17,Poland,Prof. Eribelto Manoel Reino State Airport,BR,Brazil,SAM,South America,5/3/2022,SJP,Randa Westhoff,Cancelled
58769,26040,Consuela,Strelitzki,Female,46,Russia,Gustavo Rojas Pinilla International Airport,CO,Colombia,SAM,South America,5/21/2022,ADZ,Consuela Strelitzki,Delayed
17445,89535,Cassius,Symington,Male,61,Bolivia,Sierra Maestra Airport,CU,Cuba,NAM,North America,3/9/2022,MZO,Cassius Symington,Delayed
19663,58618,Nickolai,Plomer,Male,86,Slovenia,Miyanmin Airport,PG,Papua New Guinea,OC,Oceania,9/23/2022,MPX,Nickolai Plomer,Delayed
71020,95145,Flinn,Craigmyle,Male,3,Sweden,Flamingo Airport,CR,Costa Rica,NAM,North America,1/19/2022,FMG,Flinn Craigmyle,On Time

In [13]:
df.shape

(98619, 15)

In [15]:
df.columns

Index(['Passenger ID', 'First Name', 'Last Name', 'Gender', 'Age',
       'Nationality', 'Airport Name', 'Airport Country Code', 'Country Name',
       'Airport Continent', 'Continents', 'Departure Date', 'Arrival Airport',
       'Pilot Name', 'Flight Status'],
      dtype='str')

In [17]:
df.dtypes

Passenger ID            int64
First Name                str
Last Name                 str
Gender                    str
Age                     int64
Nationality               str
Airport Name              str
Airport Country Code      str
Country Name              str
Airport Continent         str
Continents                str
Departure Date            str
Arrival Airport           str
Pilot Name                str
Flight Status             str
dtype: object

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98619 entries, 0 to 98618
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Passenger ID          98619 non-null  int64
 1   First Name            98619 non-null  str
 2   Last Name             98619 non-null  str
 3   Gender                98619 non-null  str
 4   Age                   98619 non-null  int64
 5   Nationality           98619 non-null  str
 6   Airport Name          98619 non-null  str
 7   Airport Country Code  98619 non-null  str
 8   Country Name          98619 non-null  str
 9   Airport Continent     98619 non-null  str
 10  Continents            98619 non-null  str
 11  Departure Date        98619 non-null  str
 12  Arrival Airport       98619 non-null  str
 13  Pilot Name            98619 non-null  str
 14  Flight Status         98619 non-null  str
dtypes: int64(2), str(13)
memory usage: 11.3 MB

In [20]:
df.describe()

       Passenger ID           Age
count  98619.000000  98619.000000
mean   55168.689522     45.504021
std    25985.443696     25.929849
min    10000.000000      1.000000
25%    32608.000000     23.000000
50%    55338.000000     46.000000
75%    77695.000000     68.000000
max    99999.000000     90.000000

In [24]:
df.nunique()

Passenger ID            59871
First Name               8437
Last Name               41658
Gender                      2
Age                        90
Nationality               240
Airport Name             9062
Airport Country Code      235
Country Name              235
Airport Continent           6
Continents                  6
Departure Date            364
Arrival Airport          9024
Pilot Name              98610
Flight Status               3
dtype: int64

In [25]:
df[["First Name", "Last Name", "Gender", "Age"]]

       First Name  Last Name  Gender  Age
0          Edithe     Leggis  Female   62
1          Elwood       Catt    Male   62
2           Darby    Felgate    Male   67
3        Dominica       Pyle  Female   71
4             Bay    Pencost    Male   21
...           ...        ...     ...  ...
98614      Gareth    Mugford    Male   85
98615       Kasey   Benedict  Female   19
98616      Darrin     Lucken    Male   65
98617       Gayle  Lievesley  Female   34
98618  Wilhelmine     Touret  Female   10

[98619 rows x 4 columns]

In [26]:
df[["Nationality", "Country Name", "Flight Status"]]

      Nationality        Country Name Flight Status
0           Japan       United States       On Time
1       Nicaragua              Canada       On Time
2          Russia              France       On Time
3           China              Canada       Delayed
4           China       United States       On Time
...           ...                 ...           ...
98614       China              Norway     Cancelled
98615      Russia          Madagascar     Cancelled
98616   Indonesia               Spain       On Time
98617       China       Côte d'Ivoire     Cancelled
98618      Poland  Russian Federation       Delayed

[98619 rows x 3 columns]

In [29]:
df[["Age"]]

       Age
0       62
1       62
2       67
3       71
4       21
...    ...
98614   85
98615   19
98616   65
98617   34
98618   10

[98619 rows x 1 columns]

In [30]:
df["Age"].mean()

np.float64(45.50402052342855)

In [31]:
df["Age"].min()

np.int64(1)

In [32]:
df["Age"].max()

np.int64(90)

In [34]:
df["Age"].median()

np.float64(46.0)

In [35]:
df["Age"].std()

np.float64(25.92984855207266)